#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOSQL
CREATE USER tour_app WITH PASSWORD '${APP_DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO tour_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO tour_app;
EOSQL